### PR TITLE
Writing a README for the JSOL lib

### PR DESCRIPTION
**Pull request by ndrwnaguib**
Please check the README written for this library. There are many details that should be added after submitting the lib's paper. Waiting for review.

### CODE REVIEW

**Comment by YusufMohamed** [comment]
Did Dr. Waleed approve on the naming  "JSOL"? @andrewnaguib

**Comment by ndrwnaguib** [comment]
@YusufMohamed I believe he did; since *GOG* was so confusing that could be meaning "Grammar of Graphics" instead.

**Comment by DrWaleedAYousef** [comment]
Thanks so much. Just three comments:
- For the book, write the full citation of the book in-text (in the same line) and remove the Amazon link.
- Add the names of the other three colleagues of the first GP. Their information is already in one of the "issues".
- The license can be MIT; right?
- The "howpublished" field of the citation can be removed.

Thanks so much.

**Comment by ndrwnaguib** [comment]
You're very welcome Prof., 

Regarding the license, it actually depends on how you wish the library to be reused. For myself, I usually prefer to use GPL v3 to force the contribution to the opensource.

**Pull request merged**
